use crate::error::Result;
use crate::llm::OperationPlan;

pub struct BpfCodeGenerator;

impl BpfCodeGenerator {
    pub fn generate_from_plan(plan: &OperationPlan) -> Result<String> {
        // The LLM already provides the code snippet, but we can enhance it
        let mut code = String::new();

        // Add necessary headers
        code.push_str(
            r#"// Auto-generated by Scalpel
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

"#,
        );

        // Add the LLM-generated code
        code.push_str(&plan.implementation.code_snippet);
        code.push('\n');

        // Add license (required for BPF programs)
        code.push_str("\nchar LICENSE[] SEC(\"license\") = \"GPL\";\n");

        Ok(code)
    }

    pub fn generate_simple_tracer(function_name: &str, offset: Option<u64>) -> Result<String> {
        let probe_name = if let Some(off) = offset {
            format!("{}+{:#x}", function_name, off)
        } else {
            function_name.to_string()
        };

        let code = format!(
            r#"// Simple tracer for {}
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

SEC("kprobe/{}")
int trace_{}(struct pt_regs *ctx) {{
    u64 pid = bpf_get_current_pid_tgid();
    bpf_printk("Hit {}: PID=%llu\\n", pid);
    return 0;
}}

char LICENSE[] SEC("license") = "GPL";
"#,
            probe_name, function_name, function_name.replace("::", "_"), function_name
        );

        Ok(code)
    }

    pub fn generate_arg_tracer(
        function_name: &str,
        arg_positions: &[usize],
        arg_names: &[&str],
    ) -> Result<String> {
        let mut reads = String::new();
        let mut prints = String::new();

        for (i, &pos) in arg_positions.iter().enumerate() {
            let arg_name = arg_names.get(i).unwrap_or(&"arg");
            let reg = match pos {
                0 => "PT_REGS_PARM1(ctx)",
                1 => "PT_REGS_PARM2(ctx)",
                2 => "PT_REGS_PARM3(ctx)",
                3 => "PT_REGS_PARM4(ctx)",
                4 => "PT_REGS_PARM5(ctx)",
                5 => "PT_REGS_PARM6(ctx)",
                _ => continue,
            };

            reads.push_str(&format!("    u64 {} = (u64){};\n", arg_name, reg));
            prints.push_str(&format!(" {}=%llu", arg_name));
        }

        let code = format!(
            r#"// Argument tracer for {}
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

SEC("kprobe/{}")
int trace_{}_args(struct pt_regs *ctx) {{
{}
    bpf_printk("{}:{}\n"{});
    return 0;
}}

char LICENSE[] SEC("license") = "GPL";
"#,
            function_name,
            function_name,
            function_name.replace("::", "_"),
            reads,
            function_name,
            prints,
            arg_names.iter().map(|_| ", arg").collect::<String>()
        );

        Ok(code)
    }
}
